defaults: &defaults
  encryption_key: 'ecd1ea17d44b9209c5e9eb91dff3383c'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  encryption_key: <%= ENV['ENCRYPTION_KEY']%>
